### ISSUE TITLE
Unexpectedly import PyQt5 when running under no window mode

### ISSUE THREAD

**Issue by BruceZhang1993** [feeluown/feeluown-qqmusic#17]
Logs:
```
W/python.stderr: [2021-12-21 11:51:51,069 feeluown.plugin:189] [ERROR]: Failed to load module qqmusic
    Traceback (most recent call last):
      File "/data/data/io.github.feeluown.feeluownx/files/chaquopy/AssetFinder/requirements/feeluown/plugin.py", line 187, in _scan_entry_points
        module = entry_point.load()
      File "stdlib/importlib/metadata.py", line 77, in load
      File "stdlib/importlib/__init__.py", line 127, in import_module
W/python.stderr:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "bootstrap/java/android/importer.py", line 532, in exec_module
      File "<frozen importlib._bootstrap_external>", line 843, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/data/data/io.github.feeluown.feeluownx/files/chaquopy/AssetFinder/requirements/fuo_qqmusic/__init__.py", line 6, in <module>
        from .ui import UiManager
      File "import.pxi", line 60, in java.chaquopy.import_override
      File "/data/data/io.github.feeluown.feeluownx/files/chaquopy/AssetFinder/requirements/fuo_qqmusic/ui.py", line 8, in <module>
        from feeluown.gui.widgets.login import CookiesLoginDialog, InvalidCookies
      File "import.pxi", line 60, in java.chaquopy.import_override
      File "/data/data/io.github.feeluown.feeluownx/files/chaquopy/AssetFinder/requirements/feeluown/gui/widgets/__init__.py", line 1, in <module>
        from .textbtn import TextButton
      File "import.pxi", line 60, in java.chaquopy.import_override
      File "/data/data/io.github.feeluown.feeluownx/files/chaquopy/AssetFinder/requirements/feeluown/gui/widgets/textbtn.py", line 1, in <module>
        from PyQt5.QtWidgets import QPushButton
      File "import.pxi", line 60, in java.chaquopy.import_override
      File "import.pxi", line 20, in java.chaquopy.import_override
    ModuleNotFoundError: No module named 'PyQt5'
```

**Comment by BruceZhang1993** [comment]
Fixed
