### ISSUE TITLE
show_provider_current_user_playlists: Not a valid URL

### ISSUE THREAD

**Issue by FlyGoat** [feeluown/feeluown-qqmusic#21]
Hi,

在从feeluown UI登录账号之后得到了如下报错:

```
[2024-03-02 09:59:15,283 qasync._QEventLoop:739] [ERROR]: Task exception was never retrieved
future: <Task finished name='Task-17' coro=<LeftPanel.show_provider_current_user_playlists() done, defined at /usr/lib/python3.11/site-packages/feeluown/gui/uimain/sidebar.py:104> exception=ValidationError({'logo': ['Not a valid URL.']})>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/feeluown/gui/uimain/sidebar.py", line 109, in show_provider_current_user_playlists
    reader = await run_fn(provider.current_user_fav_create_playlists_rd)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qasync/__init__.py", line 150, in run
    r = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fuo_qqmusic/provider.py", line 289, in current_user_fav_create_playlists_rd
    return [_deserialize(playlist, QQPlaylistSchema) for playlist in playlists]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fuo_qqmusic/provider.py", line 289, in <listcomp>
    return [_deserialize(playlist, QQPlaylistSchema) for playlist in playlists]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fuo_qqmusic/provider.py", line 304, in _deserialize
    obj = schema.load(data)
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/marshmallow/schema.py", line 723, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/marshmallow/schema.py", line 910, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'logo': ['Not a valid URL.']}
```

同时无法显示歌单。

请帮忙排查，谢谢。

**Comment by FlyGoat** [comment]
@cosven 非常感谢，问题解决了，不知道方不方便Tag一个Release，这样发行版可以马上更新。

**Comment by cosven** [comment]
https://github.com/feeluown/feeluown-qqmusic/commit/416182cbfc78687126444a0761c10ce7906e60fb
发了 1.0.2 的新版本。
